[Rule]
# OPENAI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list
# Claude
DOMAIN,api.anthropic.com
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX.com
DOMAIN-SUFFIX.ai
DOMAIN-SUFFIXusercontent.com
DOMAIN-SUFFIX,segment.io
DOMAIN-SUFFIX,segment.com