[Rule]
# OPENAI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,PROXY
# Claude
DOMAIN,api.anthropic.com,PROXY
DOMAIN-SUFFIX,anthropic.com,PROXY
DOMAIN-SUFFIX.com,PROXY
DOMAIN-SUFFIX.ai,PROXY
DOMAIN-SUFFIXusercontent.com,PROXY
DOMAIN-SUFFIX,segment.io,PROXY
DOMAIN-SUFFIX,segment.com,PROXY